version: '3.8'

services:
  server:
    build: ./server
    command: npm run dev
    ports:
      - "3001:3001"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
      MYSQL_DATABASE: lost_and_found
    depends_on:
      - mysql
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules

  client:
    build: ./client
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: lost_and_found
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d

volumes:
  mysql_data:
